### ISSUE TITLE
unexepected keyword argument 'sp_dc'

### ISSUE THREAD

**Issue by gehringf** [fondberg/spotcast#104]
I've followed the instructions and added the cookie values to my secrets and config.

Config: 
```
…
spotcast:
  sp_dc: !secret spotcast_client
  sp_key: !secret spotcast_key
…
```

secrets.yml:
```
…
spotcast_client: asdf***asdf
spotcast_key: asdf***asdf
…
```

When using the dev tools to start a stream, I receive this error message:

`Fehler beim Aufrufen des Service spotcast/start.`
`get_spotify_token() got an unexpected keyword argument 'sp_dc'`

What am I missing?
I've tried adding quotes to the values in secrets.yml. 
I've tried logging in again and receiving new tokens.
That didn't help.
What else can I try?

Thank you for building this!

**Comment by rmatta91** [comment]
Hello Im facing the same issue after updating the component to v3.2. It used to be working before

**Comment by fondberg** [comment]
It seems 3.2 has a problem.  I'll fix it tomorrow morning. In the meantime use the older version

**Comment by mauro967** [comment]
It is true you have this problem, I downgraded it and now it works. thanks for this and good job

**Comment by fondberg** [comment]
Should be fixed in v3.2.1

**Comment by gehringf** [comment]
Can confirm, the fix works. Thank you for being so damn quick 👏
