### ISSUE TITLE
AttributeError: module 'pychromecast' has no attribute 'get_chromecast_from_cast_info'

### ISSUE THREAD

**Issue by Atiunderscore** [fondberg/spotcast#183]
Hello,

After update v3.5.2 I'm getting the following error:

```
Error executing script. Unexpected error for call_service at pos 2: module 'pychromecast' has no attribute 'get_chromecast_from_cast_info'
While executing automation automation.switch_spotcast
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 457, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1484, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 369, in start_casting
    spotify_cast_device = SpotifyCastDevice(
  File "/config/custom_components/spotcast/__init__.py", line 502, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 526, in getChromecastDevice
    return pychromecast.get_chromecast_from_cast_info(
AttributeError: module 'pychromecast' has no attribute 'get_chromecast_from_cast_info'
```

My automation looks like this:

```
- service: spotcast.start
  data:
    entity_id: media_player.alle_speakers
    uri: spotify:playlist:46vPUPIAf7mjyTrJzJcjpi
    random_song: true
    shuffle: true
```

**Comment by hmmbob** [comment]
Are you on an old Home Assistant version maybe? Because that has been added over 12 months ago....

**Comment by ohipe** [comment]
Same here, after update to 3.5.2 on HA core-2021.3.4

**Comment by Atiunderscore** [comment]
> Are you on an old Home Assistant version maybe? Because that code has been added over 12 months ago....

I'm on version 2021.1.5 at the moment.

**Comment by hmmbob** [comment]
Well, as with most issues..... Try upgrading to the latest version first.

**Comment by sermayoral** [comment]
> Same here, after update to 3.5.2 on HA core-2021.3.4

The requirement for the 3.5.2 spotcast version is HA >= 2021.4.0

**Comment by ohipe** [comment]
@sermayoral Sorry I miss this info, now it works despite some errors in log:
- Known devices: []
- No device with id "xxx" known by Spotify
Anyway, now service spotcast.start works.

thanks

**Comment by Atiunderscore** [comment]
> > Same here, after update to 3.5.2 on HA core-2021.3.4
> 
> The requirement for the 3.5.2 spotcast version is HA >= 2021.4.0

Updated to the latest version of HA and works like a charm. Thanks!
