### ISSUE TITLE
Cannot load on beta 2021.12.0b.0

### ISSUE THREAD

**Issue by Bluhme1** [fondberg/spotcast#269]
After upgrading to the new beta the Spotcast cannot load.

The release notes say that Spotipy has been upgraded to 2.19.0

**Comment by hmmbob** [comment]
What's in your logs?

**Comment by hmmbob** [comment]
Seeing this too. Logs:

```py
2021-12-04 11:12:35 ERROR (MainThread) [homeassistant.components.script.start_music_t] Slaaptijd: Error executing script. Unexpected error for call_service at pos 2: 'ChromecastInfo' object has no attribute 'cast_type'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1534, in _execute_service
await self._hass.async_add_executor_job(handler.job.target, service_call)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/spotcast/__init__.py", line 156, in start_casting
spotify_device_id = spotcast_controller.get_spotify_device_id(
File "/config/custom_components/spotcast/spotcast_controller.py", line 196, in get_spotify_device_id
spotify_cast_device = SpotifyCastDevice(
File "/config/custom_components/spotcast/spotcast_controller.py", line 51, in __init__
self.castDevice = self.getChromecastDevice(device_name)
File "/config/custom_components/spotcast/spotcast_controller.py", line 70, in getChromecastDevice
return pychromecast.get_chromecast_from_cast_info(
File "/usr/local/lib/python3.9/site-packages/pychromecast/__init__.py", line 69, in get_chromecast_from_cast_info
return Chromecast(
File "/usr/local/lib/python3.9/site-packages/pychromecast/__init__.py", line 271, in __init__
if not cast_info.cast_type:
AttributeError: 'ChromecastInfo' object has no attribute 'cast_type'
2021-12-04 11:12:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140433329171808] 'ChromecastInfo' object has no attribute 'cast_type'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 273, in service_handler
await script_entity.async_turn_on(
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 377, in async_turn_on
await coro
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 403, in _async_run
return await self.script.async_run(script_vars, context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1259, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1534, in _execute_service
await self._hass.async_add_executor_job(handler.job.target, service_call)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/spotcast/__init__.py", line 156, in start_casting
spotify_device_id = spotcast_controller.get_spotify_device_id(
File "/config/custom_components/spotcast/spotcast_controller.py", line 196, in get_spotify_device_id
spotify_cast_device = SpotifyCastDevice(
File "/config/custom_components/spotcast/spotcast_controller.py", line 51, in __init__
self.castDevice = self.getChromecastDevice(device_name)
File "/config/custom_components/spotcast/spotcast_controller.py", line 70, in getChromecastDevice
return pychromecast.get_chromecast_from_cast_info(
File "/usr/local/lib/python3.9/site-packages/pychromecast/__init__.py", line 69, in get_chromecast_from_cast_info
return Chromecast(
File "/usr/local/lib/python3.9/site-packages/pychromecast/__init__.py", line 271, in __init__
if not cast_info.cast_type:
AttributeError: 'ChromecastInfo' object has no attribute 'cast_type'
```

**Comment by hmmbob** [comment]
Probably caused by https://github.com/home-assistant/core/pull/60205

**Comment by Bluhme1** [comment]
Should we raise an issue in the Core?
Can you do that posting the log @hmmbob ?

**Comment by hmmbob** [comment]
It needs to be changed in Spotcast, as per maintainer of `pychromecast`

> Mention these core PRs in the spotcast ticket:
> - https://github.com/home-assistant/core/pull/59719
> - https://github.com/home-assistant/core/pull/60205

**Comment by Bluhme1** [comment]
Ok. Thank you. We will have to wait for Fondberg & Co, then

**Comment by hmmbob** [comment]
It might be a fairly easy fix, I think I fixed it locally. Willing to try?

in file `spotcast_controller.py`, change line 71 by adding an additional `.cast_info` so it reads:
```py
                cast_info.cast_info, ChromeCastZeroconf.get_zeroconf()
```

Restart HA and see if it is fixed

**Comment by Bluhme1** [comment]
Didn't work for me. Same error in log

**Comment by Bluhme1** [comment]
When I com to think of it my error log is maybe different from yours

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/spotcast/__init__.py:128 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 11.36.19 (515 occurrences) 
Last logged: 12.10.54

[140631677502464] Error handling message: Unknown error
[140631677476768] Error handling message: Unknown error
[140631651035792] Error handling message: Unknown error
[140631687929040] Error handling message: Unknown error
[140631686429952] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/spotcast/__init__.py", line 125, in websocket_handle_castdevices
    resp = [
  File "/config/custom_components/spotcast/__init__.py", line 128, in <listcomp>
    "model_name": cast_info.model_name,
AttributeError: 'ChromecastInfo' object has no attribute 'model_name'

**Comment by hmmbob** [comment]
> When I com to think of it my error log is maybe different from yours
> 
> Logger: homeassistant.components.websocket_api.http.connection Source: custom_components/spotcast/**init**.py:128 Integration: Home Assistant WebSocket API (documentation, issues) First occurred: 11.36.19 (515 occurrences) Last logged: 12.10.54
> 
> [140631677502464] Error handling message: Unknown error [140631677476768] Error handling message: Unknown error [140631651035792] Error handling message: Unknown error [140631687929040] Error handling message: Unknown error [140631686429952] Error handling message: Unknown error Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle handler(self.hass, self, schema(msg)) File "/config/custom_components/spotcast/**init**.py", line 125, in websocket_handle_castdevices resp = [ File "/config/custom_components/spotcast/**init**.py", line 128, in "model_name": cast_info.model_name, AttributeError: 'ChromecastInfo' object has no attribute 'model_name'

Ah, the error is different, but the fix is in the PR too.

In your case the sensor failed, in my case starting a stream failed. Both are fixed in #271

**Comment by Bluhme1** [comment]
You're the man. Everything works again, so your PR is ready for merging. Thank you very much

**Comment by FrancoLoco** [comment]
Mine loads but when I want to start casting in my automation it does this even with the patch: ChromecastInfo' object has no attribute 'cast_type'

**Comment by FrancoLoco** [comment]
Wait I might have applied the patch incorrectly

**Comment by Bluhme1** [comment]
Will your PR be merged soon as an update to the custom component from Fondberg?

**Comment by FrancoLoco** [comment]
I managed to patch correctly and it does work thanks
