### PR TITLE
Authenticate using cookies

### LINKED ISSUE #84: 400 error on login.
Have tested creds on spotify web player as well as spotify dev portal, but still getting the following error:

**_"400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login"_**

configuration in configuration.yaml is: 
```
spotcast:
  username: !secret spotify_username
  password: !secret spotify_password
  accounts:
      alan:
        username: !secret spotify_username
        password: !secret spotify_password
```
Have tried with and without the `accounts:` section.  Made sure both secrets and config don't contain any leading/trailing spaces or other characters.

Running hass.io .108.9 and spotcast 2.91 (says 2.92 is available but requires hass .109 (which isn't available yet).  Ubuntu 18.04 on NUC.

### LINKED ISSUE #87: Seems to be broken after upgrade of HA to 0.110
Hi!

Upgraded to HA 0.110 and got the below in my log and it refuses to start:

Package spotcast setup failed. Component spotcast cannot import name 'APP_SUPLA' from 'pychromecast.config' (/usr/local/lib/python3.7/site-packages/pychromecast/config.py)
Platform error sensor.spotcast - cannot import name 'APP_SUPLA' from 'pychromecast.config' (/usr/local/lib/python3.7/site-packages/pychromecast/config.py)

------------
I believe it is due to python that is version 3.8 in HA 0.110 but I do not know.

### PR DESCRIPTION
**Pull request by petergp**
Closes #84 and closes #87

### CODE REVIEW

**Comment by petergp** [comment]
This also bump of Pychromecast to 5.2.0. Let me know if you want me to change anything. I added some stuff to the README too.

I will let it be up to you to decide if you want to wait for https://github.com/enriquegh/spotify-webplayer-token/pull/8 to be merged or just go ahead with this release for now and fix the dependency later.

**Comment by fondberg** [comment]
Great! I'll release it tomorrow as I need to update some packages and do a final test.
 Thanks for all hard work!

**Comment by enriquegh** [comment]
@fondberg @petergp version 1.0 of spotify-token is released!
https://pypi.org/project/spotify-token/1.0.0/

Thanks for the fix!

**Comment by petergp** [comment]
@enriquegh Awesome, thanks!

@fondberg I've updated the PR to point to `spotify-token` 1.0.0

**Comment by fondberg** [comment]
Great! 👍💪🏋️‍♂️
