### ISSUE TITLE
Spotcast breaks with HA 2024.10.0b0

### ISSUE THREAD

**Issue by hmmbob** [fondberg/spotcast#460]
# Bug Ticket

## Describe the bug

Spotcast breaks when you upgrade from HA 2024.9 to 2024.10

Likely a regression because of https://github.com/home-assistant/core/pull/123548

## Troubleshooting

Make sure to validate all the elements before submitting the ticket (Exception to the steps marked as optional)

* [X] Using latest version of spotcast
* [beta] Using latest stable version of Home Assistant
* [X] I have setup the Spotify integration in Home Assistant
* [X] I have renewed my `sp_dc` and `sp_key` values and restarted Home Assistant (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [X] (optional) I have Spotify Premium
* [ ] (optional) I am using multiple accounts
* [ ] (optional) I'm attaching relevant logs with level debug for component spotcast (see [README](https://github.com/fondberg/spotcast#enabling-debug-log))
* [ ] (optional) I'm using entity_id in the service call and have tried device_name but the issue remains

## Environment

 - Installation type: Container
 - HA version: 2024.10.0b0
 - spotcast version: 3.8.1

## Logs

* normal

````py
2024-09-26 21:01:41.484 ERROR (MainThread) [homeassistant.components.script.start_music_t] Slaaptijd: Error executing script. Unexpected error for call_service at pos 2: 'SpotifyMediaPlayer' object has no attribute 'data'
Traceback (most recent call last):
File "/config/custom_components/spotcast/helpers.py", line 39, in get_spotify_media_player
entity_devices = entity._devices
^^^^^^^^^^^^^^^
AttributeError: 'SpotifyMediaPlayer' object has no attribute '_devices'. Did you mean: 'devices'?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
return await long_task
^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2811, in _execute_service
return await self._hass.async_add_executor_job(target, service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/__init__.py", line 256, in start_casting
spotify_device_id = spotcast_controller.get_spotify_device_id(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/spotcast_controller.py", line 284, in get_spotify_device_id
spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/spotcast_controller.py", line 268, in _getSpotifyConnectDeviceId
media_player = get_spotify_media_player(self.hass, client._get("me")["id"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/helpers.py", line 41, in get_spotify_media_player
entity_devices = entity.data.devices.data
^^^^^^^^^^^
AttributeError: 'SpotifyMediaPlayer' object has no attribute 'data'
2024-09-26 21:01:41.491 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/config/custom_components/spotcast/helpers.py", line 39, in get_spotify_media_player
entity_devices = entity._devices
^^^^^^^^^^^^^^^
AttributeError: 'SpotifyMediaPlayer' object has no attribute '_devices'. Did you mean: 'devices'?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 707, in _async_run
return await self.script.async_run(script_vars, context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1795, in async_run
return await asyncio.shield(create_eager_task(run.async_run()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 557, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
return await long_task
^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2811, in _execute_service
return await self._hass.async_add_executor_job(target, service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/__init__.py", line 256, in start_casting
spotify_device_id = spotcast_controller.get_spotify_device_id(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/spotcast_controller.py", line 284, in get_spotify_device_id
spotify_device_id = self._getSpotifyConnectDeviceId(client, device_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/spotcast_controller.py", line 268, in _getSpotifyConnectDeviceId
media_player = get_spotify_media_player(self.hass, client._get("me")["id"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/helpers.py", line 41, in get_spotify_media_player
entity_devices = entity.data.devices.data
^^^^^^^^^^^
AttributeError: 'SpotifyMediaPlayer' object has no attribute 'data'
````

**Comment by FrancoLoco** [comment]
I have the same problem thanks

**Comment by fcusson** [comment]
Home assistant must have changed the structure of the media player entity.

We could print to debug the Dir of the object

**Comment by fcusson** [comment]
Seems that they moved `SpotifyMediaPlayer.data.devices` to `SpotifyMediaPlayer.devices`. Testing if it resolves the issue

**Comment by fcusson** [comment]
ok can confirm the issue is with the new coordinator. We used to have access to a `device` callable that would provide the devices linked to an account, but devices is now a `DataUpdateCoordinator`. I don't have enough detail yet to understand how to interact with these Coordinator, I'll try to do some digging, but if others can help I wouldn't mind

**Comment by fcusson** [comment]
ok found the solution, had to add the `hass` object to the get_spotify_device_id function to force the refresh of the data. Its now working.

This might be a really good improvement, because that would also mean we can force refresh the list of devices now.

**Comment by fcusson** [comment]
Tested in version `2024.10.0b4` and `2024.9.3`. Both working without issues. I'm going to release the preventive fix for the beta

**Comment by fcusson** [comment]
Closing with release of `v3.8.2` Please reopen of bug still appears from your side

**Comment by Flibbmaster** [comment]
For me, Version 3.8.2 does not work on HA 2024.9.3.
I updated today, directly after the restart the playlists and players stay empty in spotcard.
Protocol monitors some errors:

> Logger: homeassistant
> Quelle: custom_components/spotcast/__init__.py:146
> Integration: Spotcast (Dokumentation, Probleme)
> Erstmals aufgetreten: 15:23:32 (1 Vorkommnisse)
> Zuletzt protokolliert: 15:23:32
> 
> Error doing job: Task exception was never retrieved (None)
> Traceback (most recent call last):
>   File "/config/custom_components/spotcast/helpers.py", line 122, in run
>     return await loop.run_in_executor(executor, pfunc)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/spotcast/__init__.py", line 146, in get_devices
>     resp = get_spotify_devices(spotify_media_player)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: get_spotify_devices() missing 1 required positional argument: 'hass'

Going back to 3.8.1 and everything works as expected.

**Comment by hmmbob** [comment]
Works for 2024.10 indeed, thanks.

@fcusson To fix 

> For me, Version 3.8.2 does not work on HA 2024.9.3. I updated today, directly after the restart the playlists and players stay empty in spotcard. Protocol monitors some errors:
> 
> Going back to 3.8.1 and everything works as expected.

You could raise the HA version in hacs.json to 2024.10.0b0:

https://github.com/fondberg/spotcast/blob/cb2f905a6c62022b4a97a0f611026c409e661e3f/hacs.json#L4

**Comment by fcusson** [comment]
@hmmbob 
hmmm... I added new validation, we should still hit the old structure first, this is weird. I'll take a look, can you give me a link to the spotcard you are using?

**Comment by hmmbob** [comment]
Oh, it's working for me! 

You need @Flibbmaster support

**Comment by fcusson** [comment]
@hmmbob 

> Oh, it's working for me!

Sorry misread that part

@Flibbmaster if you could provide some details, I might have the spotcard you are mentionning in my regression tests

**Comment by Flibbmaster** [comment]
Hi, @fcusson ,

Using this Lovelace Card from HACS:
https://community.home-assistant.io/t/spotify-lovelace-card/103525

**Comment by fcusson** [comment]
ok thanks, I'll check, but I know it is now breaking a lot. I don't have access to this project from Fondberg, I'll see what I can do, but it might become an abandonware saddly.

**Comment by Flibbmaster** [comment]
@fcusson 
Totally understood, that card is not from you, so no responsibility on your side.
For me it was just the easiest way to implement the playlists and players in a single card in the Dashboard.

**Comment by MDV85** [comment]
Same.... Spotify Card not work after update to ver. 3.8.2 ...(((  https://github.com/custom-cards/spotify-card

**Comment by Pirol62** [comment]
It doesn't work on 2024.8.3 either. Does anybody know how to downgrade?

**Comment by PerSterin** [comment]
If you have this error, change line 146 of init.py. and restart HA. See error in logger below.

From: resp = get_spotify_devices(spotify_media_player)
To: resp = get_spotify_devices(spotify_media_player, hass)

This solved my problem

Logger: homeassistant
Source: custom_components/spotcast/init.py:146
integration: Spotcast (documentation, issues)
First occurred: 15:38:48 (4 occurrences)
Last logged: 15:39:16

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/config/custom_components/spotcast/helpers.py", line 122, in run
return await loop.run_in_executor(executor, pfunc)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spotcast/init.py", line 146, in get_devices
resp = get_spotify_devices(spotify_media_player)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_spotify_devices() missing 1 required positional argument: 'hass'

**Comment by Flibbmaster** [comment]
But @PerSterin: Isn´t this undoing the changes from Version 3.8.2?
So it won´t work with HA 2024.10 then, right ?

**Comment by PerSterin** [comment]
I don't know what was done in the last update on the spotcast. But this works in latest beta. Probably missed a place in the code to correct with get_spotify_devices(spotify_media_player, hass) but I don't know. Running the latest beta now.

![HA](https://github.com/user-attachments/assets/a6237dcf-ce8f-4c02-8b29-596dd2c5fc32)
![HA2](https://github.com/user-attachments/assets/9914c473-8a27-4060-9b9b-a1d17b336020)

**Comment by Zagor4** [comment]
@PerSterin could you please share the code of your Spotify lovelace card with media player commands ? 
Thanks a lot

**Comment by PerSterin** [comment]
@Zagor4
I suspect you mean this card if not get back to me.

Spotify-card 
[https://github.com/custom-cards/](url)

**Comment by Flibbmaster** [comment]
Hi @PerSterin,

i just updated from HA 2024.9.3 to HA 2024.10.0 today, and i can confirm your solution 

> If you have this error, change line 146 of init.py. and restart HA. See error in logger below.
> 
> From: resp = get_spotify_devices(spotify_media_player)
> To: resp = get_spotify_devices(spotify_media_player, hass)

works fine for the combination of Spotcast 3.8.2 and the Spotify Lovelace Card [https://community.home-assistant.io/t/spotify-lovelace-card/103525](url)

**Comment by Zagor4** [comment]
@PerSterin no, i'm speaking about your card (you posted a screen with a media player card over the spotify card!
I'm not able to sync spotify card with media player card that expose stop / play / next song / previous song.

Thanks a lot

**Comment by PerSterin** [comment]
Hi @Zagor4 
Ok: Media control Card configuration 

type: media-control
entity: media_player.vardagsrum
visibility:
  - condition: or
    conditions:
      - condition: state
        entity: media_player.vardagsrum
        state: playing
      - condition: state
        entity: media_player.vardagsrum
        state: paused
      - condition: state
        entity: media_player.vardagsrum
        state: buffering
  - condition: state
    entity: media_player.alla
    state: "off"
layout_options:
  grid_columns: 4
  grid_rows: 3

**Comment by fcusson** [comment]
Should be fixed in [v3.9.0](https://github.com/fondberg/spotcast/releases/tag/v3.9.0)

@PerSterin, @Flibbmaster, can you confirm?

**Comment by tivoo** [comment]
Can confirm the error is gone now and the Spotify card works again! Thanks @fcusson

**Comment by PerSterin** [comment]
Can confirm the error is gone, Spotify card works again! Thanks @fcusson

**Comment by Flibbmaster** [comment]
Yes, no problem after update. Thanks @fcusson

**Comment by fcusson** [comment]
Closing for issue fixed

**Comment by eugsmiley** [comment]
So how do I correct a Spotcast Home Assistant script that relies on the 'data:' object?

If I try to build it in the UI, I  can only choose one URI. I use a template to pick a random one. As soon as I put the template in it switches to YAML mode with a 'data:' object structure. When I play it I get the 'AttributeError: 'SpotifyMediaPlayer' object has no attribute 'data'' error.

If I don't put it the template, I still get the error. Looking at the YAML, it still has a data attribute.

```
alias: New Spotcast
sequence:
  - action: spotcast.start
    metadata: {}
    data:
      force_playback: false
      random_song: true
      shuffle: true
      entity_id: media_player.living_room_display
description: ""
```

**Comment by fcusson** [comment]
@eugsmiley this is a different issue.

Also, please do not add comments to a closed issue, even worst without mention, I only saw your comment because I wnated to revalidate something in that thread. The problem is very not normal and this is a first. Please open a ticket, fill the report bug properly with all the information requested.

Also I will need debug logs and the script you are trying to run

**Comment by javiges** [comment]
With the latest version of HA and the latest version of Spotcast, the list still doesn't appear. Is there something I can do? Thanks.
