### ISSUE TITLE
ImportError: cannot import name 'SENSOR_SCAN_INTERVAL_SECS' from 'homeassistant.const'

### ISSUE THREAD

**Issue by syphernl** [fondberg/spotcast#111]
After updating to 3.2.2 on HASS 0.112.1 I'm seeing this error in my logs while starting up:

```
2020-07-03 15:34:02 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/config.py", line 780, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/hass/lib/python3.8/site-packages/homeassistant/loader.py", line 321, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hass/.homeassistant/custom_components/spotcast/sensor.py", line 6, in <module>
    from homeassistant.const import STATE_OK, STATE_UNKNOWN, SENSOR_SCAN_INTERVAL_SECS
ImportError: cannot import name 'SENSOR_SCAN_INTERVAL_SECS' from 'homeassistant.const' (/srv/hass/lib/python3.8/site-packages/homeassistant/const.py)
```

A config test shows the same issue:
```
Failed config
  General Errors:
    - Platform error sensor.spotcast - cannot import name 'SENSOR_SCAN_INTERVAL_SECS' from 'homeassistant.const' (/srv/hass/lib/python3.8/site-packages/homeassistant/const.py)
```

**Comment by fondberg** [comment]
Revert to old version. I must have mafe a mistake. Will fix tomorrow

**Comment by fondberg** [comment]
Fixed in https://github.com/fondberg/spotcast/releases/tag/v3.2.3
