### ISSUE TITLE
Error after the last update

### ISSUE THREAD

**Issue by Dskurihin** [fondberg/spotcast#125]
After the update to 3.4.2 I see the error in logs when I'm trying to cast:
'ChromecastInfo' object has no attribute 'services'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1299, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/spotcast/__init__.py", line 299, in start_casting
    hass, call.data.get(CONF_DEVICE_NAME), call.data.get(CONF_ENTITY_ID)
  File "/config/custom_components/spotcast/__init__.py", line 402, in __init__
    self.castDevice = self.getChromecastDevice(device_name)
  File "/config/custom_components/spotcast/__init__.py", line 431, in getChromecastDevice
    cast_info.services,
AttributeError: 'ChromecastInfo' object has no attribute 'services'

Place seems to be the same that was changed in last pull request.

**Comment by fondberg** [comment]
What version of HA are you running? The latest works fine for many people

**Comment by Sebash93** [comment]
I'm having the same issue for version 3.4.2. It was working perfectly before.

I have a NODE-Red automation linea and when i try to call the service this is what i get: "Call-service API error.  Error Message: 'ChromecastInfo' object has no attribute 'services'".

**Comment by fondberg** [comment]
Must be a breaking change in their api. I will have a look at it as soon as I have time

**Comment by Sebash93** [comment]
I downgraded to version 3.4.1 and it works perfectly

**Comment by fondberg** [comment]
I can't reproduce this. I'm running latest HA (105.2) and latest spotcast. Can you reinstall spotcast to see if there is some python library inconsistency?

**Comment by RaveWithGrin** [comment]
Running 110.2, same issue.

**Comment by fondberg** [comment]
110.2 is not supported anymore

**Comment by slurpey** [comment]
Good news - the issue is solved in version 0.116.2.  I had been struggling trying to have my media players show up but stopcast was  "breaking them" - the issue resolved itself in version 116 - my automations etc also started re-working without issues.
