### ISSUE TITLE
Seems to be broken after upgrade of HA to 0.110

### ISSUE THREAD

**Issue by mbrihed** [fondberg/spotcast#87]
Hi!

Upgraded to HA 0.110 and got the below in my log and it refuses to start:

Package spotcast setup failed. Component spotcast cannot import name 'APP_SUPLA' from 'pychromecast.config' (/usr/local/lib/python3.7/site-packages/pychromecast/config.py)
Platform error sensor.spotcast - cannot import name 'APP_SUPLA' from 'pychromecast.config' (/usr/local/lib/python3.7/site-packages/pychromecast/config.py)

------------
I believe it is due to python that is version 3.8 in HA 0.110 but I do not know.

**Comment by disrupted** [comment]
can confirm, had to disable spotcast in my configuration for now

**Comment by ericpignet** [comment]
I'm getting this error after upgrade to 0.110:
Component error: spotcast - No module named 'pychromecast.quick_play'
Also had to remove spotcast from my configuration.

**Comment by fondberg** [comment]
See top of readme in both HACS and this repo regarding broke  chromecast support.
Are you using it for chromecast?

**Comment by AdrinkBeer** [comment]
I had the same error right after the update, but after some restarts of my docker container, it worked again...

**Comment by mbrihed** [comment]
Hi!
I am using it to play on my Google Home speakers.

Did try and reboot several times but still no luck. Get a notification as well as the error above when checking config.

**Comment by mbrihed** [comment]
This is the message in the notification:

The following integrations and platforms could not be set up:

cast.media_player
Please check your config.

**Comment by fondberg** [comment]
Google Home speakers are chromecast.
That is broken at the moment and most likely for a long while.

**Comment by davidrustingha** [comment]
Is there anything I can help with? I get the error: ‘Component error: spotcast - No module named 'pychromecast.quick_play'’.

**Comment by Olen** [comment]
Seems like "quick_play" was moved to a seperate module:
https://github.com/home-assistant-libs/pychromecast/commit/b022fb89f9f5a165b2171b724b9127a03be0c44d

Not sure if that is the core issue here, but it sounds related to the error "No module named 'pychromecast.quick_play'"

**Comment by fondberg** [comment]
Intim there is a way to get the web login token(see linked issue in readme) I don't think there is a point using this component.

**Comment by fondberg** [comment]
This is now fixed in v3.0.0
